// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StellarSigner.Infrastructure.DrivenAdapter.Persistence;

#nullable disable

namespace StellarSigner.Infrastructure.DrivenAdapter.Persistence.Migrations
{
    [DbContext(typeof(SignerDbContext))]
    [Migration("20260920180530_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StellarSigner.Domain.Entities.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(20, 7)
                        .HasColumnType("numeric(20,7)")
                        .HasColumnName("amount");

                    b.Property<string>("AssetCode")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("asset_code");

                    b.Property<string>("CallerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("caller_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Destination")
                        .HasMaxLength(56)
                        .HasColumnType("character varying(56)")
                        .HasColumnName("destination");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("failure_code");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("operation_type");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<string>("PublicKey")
                        .HasMaxLength(56)
                        .HasColumnType("character varying(56)")
                        .HasColumnName("public_key");

                    b.Property<Guid>("RemittanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("remittance_id");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("result");

                    b.Property<string>("TransactionHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("transaction_hash");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RequestId");

                    b.ToTable("audit_records", (string)null);
                });

            modelBuilder.Entity("StellarSigner.Domain.Entities.PartnerWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DerivationIndex")
                        .HasColumnType("bigint")
                        .HasColumnName("derivation_index");

                    b.Property<string>("DerivationPath")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("derivation_path");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(56)
                        .HasColumnType("character varying(56)")
                        .HasColumnName("public_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("DerivationIndex")
                        .IsUnique();

                    b.HasIndex("PartnerId")
                        .IsUnique();

                    b.HasIndex("PublicKey")
                        .IsUnique();

                    b.ToTable("partner_wallets", null, t =>
                        {
                            t.HasCheckConstraint("ck_partner_wallets_derivation_index", "derivation_index >= 0 AND derivation_index < 2147483648");
                        });
                });

            modelBuilder.Entity("StellarSigner.Domain.Entities.SigningRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(20, 7)
                        .HasColumnType("numeric(20,7)")
                        .HasColumnName("amount");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("asset_code");

                    b.Property<string>("AssetIssuer")
                        .IsRequired()
                        .HasMaxLength(56)
                        .HasColumnType("character varying(56)")
                        .HasColumnName("asset_issuer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(56)
                        .HasColumnType("character varying(56)")
                        .HasColumnName("destination");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("failure_code");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("failure_reason");

                    b.Property<int?>("FailureStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("failure_status_code");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("operation_type");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_hash");

                    b.Property<string>("PublicKey")
                        .HasMaxLength(56)
                        .HasColumnType("character varying(56)")
                        .HasColumnName("public_key");

                    b.Property<Guid>("RemittanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("remittance_id");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<DateTimeOffset?>("SignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_at");

                    b.Property<string>("SignedXdr")
                        .HasColumnType("text")
                        .HasColumnName("signed_xdr");

                    b.Property<string>("SignedXdrHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("signed_xdr_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("transaction_hash");

                    b.Property<string>("UnsignedXdrHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("unsigned_xdr_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("version");

                    b.Property<Guid?>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("RemittanceId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("WalletId");

                    b.ToTable("signing_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_signing_requests_amount", "amount > 0");
                        });
                });

            modelBuilder.Entity("StellarSigner.Domain.Entities.WalletDerivationCounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.Property<long>("NextIndex")
                        .HasColumnType("bigint")
                        .HasColumnName("next_index");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("wallet_derivation_counters", null, t =>
                        {
                            t.HasCheckConstraint("ck_wallet_derivation_counters_next_index", "next_index >= 0 AND next_index <= 2147483648");

                            t.HasCheckConstraint("ck_wallet_derivation_counters_singleton", "name = 'wallets'");
                        });
                });

            modelBuilder.Entity("StellarSigner.Domain.Entities.SigningRequest", b =>
                {
                    b.HasOne("StellarSigner.Domain.Entities.PartnerWallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
